### ISSUE TITLE
support negative numbers

### ISSUE THREAD

**Issue by VinSpee** [antyakushev/postcss-for#11]
Hi!

I'm using your plugin to author my library and I have the need for the following syntax:

``` scss
@for $i from -1 to 10 {
    .mg-$i {
        margin-bottom: var(--space-$i);
    }
}
```

I'd expect the output to be:

``` scss
.mg--1 {
 margin-bottom: var(--space--1);
}
.mg-0 {
  margin-bottom: var(--space-0);
}
```

etc.

Currently, it just errors and says I must provide a number, as negative numbers aren't supported. Any reason not to?

Thanks!
