### ISSUE TITLE
Compiling Same styles classes together

### ISSUE THREAD

**Issue by sandiprb** [antyakushev/postcss-for#14]
Feature Request : 
If I want to generate x number of classes with same property it compiles as individual classes and property but instead it should compile classes with a single property.

For e.g.

``` css
@for $i from 1 to 4{
  .col-sm-$i { 
    padding: 10px;
  }
}
```

Compiles to 

``` css
.col-sm-1{padding: 10px;}
.col-sm-2{padding: 10px;}
.col-sm-3{padding: 10px;}
.col-sm-4{padding: 10px;}
```

But ideally it should generate 

``` css
.col-sm-1,
.col-sm-2,
.col-sm-3,
.col-sm-4{padding: 10px;}
```

**Comment by sandiprb** [comment]
I found the solution to this with [postcss-extend](https://github.com/davidtheclark/postcss-simple-extend)

with postcss-extend I can do it as below

``` css
@define-placeholder generic-column{
        padding:10px;
}

@for $i from 1 to 4{
        .fx-col-sm-$(i) {
                @extend generic-column;
        }
}
```

though it creates empty classes if no other distinct styles provided, which can be prevented easily with [postcss-discard-empty](https://github.com/ben-eb/postcss-discard-empty)

:smile:
