### ISSUE TITLE
Feature Request: Support for...in loop

### ISSUE THREAD

**Issue by fengyuanchen** [antyakushev/postcss-for#18]
For example:

Input: 

```css
@for size in ['sm', 'md', 'lg'] {
  @for span from 1 to 4 {
    .col-$(size)-$(span) {
      width: calc(($(span) / 4) * 100)%;
    }
  }
}
```

Output:

```css
.col-sm-1 {
  width: 25%;
}
.col-sm-2 {
  width: 50%;
}
.col-sm-3 {
  width: 75%;
}
.col-sm-4 {
  width: 100%;
}
.col-md-1 {
  width: 25%;
}
.col-md-2 {
  width: 50%;
}
.col-md-3 {
  width: 75%;
}
.col-md-4 {
  width: 100%;
}
.col-lg-1 {
  width: 25%;
}
.col-lg-2 {
  width: 50%;
}
.col-lg-3 {
  width: 75%;
}
.col-lg-4 {
  width: 100%;
}
```
