### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by kentcdodds** [antyakushev/postcss-for#5]
If I try the example as-is:

``` css
@for $i from 1 to 3 {
  .b-$i { width: $i px; }
}
```

I end up with this:

![screen shot 2015-05-05 at 10 10 07 pm](https://cloud.githubusercontent.com/assets/1500684/7487384/a341b8d8-f373-11e4-82e9-85619d983259.png)

The problem is the extra space. Works without the space:

![screen shot 2015-05-05 at 10 10 17 pm](https://cloud.githubusercontent.com/assets/1500684/7487387/b5770f26-f373-11e4-9b75-a2bb0b6cf369.png)

So if I change the example to not have a space:

``` css
@for $i from 1 to 3 {
  .b-$i { width: $ipx; }
}
```

I end up with this:

![screen shot 2015-05-05 at 10 10 29 pm](https://cloud.githubusercontent.com/assets/1500684/7487390/c2cc7e0e-f373-11e4-92eb-2d38c7994da6.png)

Any way to get around this?
